DROP TABLE Country CASCADE CONSTRAINTS;
DROP TABLE Player CASCADE CONSTRAINTS;
DROP TABLE Coach CASCADE CONSTRAINTS;
DROP TABLE Matches CASCADE CONSTRAINTS;
DROP TABLE Accolades CASCADE CONSTRAINTS;
DROP TABLE MOTM CASCADE CONSTRAINTS;
DROP SEQUENCE seqCoID;
DROP SEQUENCE seqPlID;
DROP SEQUENCE seqChID;
DROP SEQUENCE seqMaSID;
DROP SEQUENCE seqAcID;
DROP SEQUENCE seqMotmID;

CREATE TABLE Country (
  name VARCHAR(50) PRIMARY KEY,
  continent VARCHAR(50) NOT NULL,
  group_letter VARCHAR(1) NOT NULL,
  wins INT NOT NULL DEFAULT 0,
  losses INT NOT NULL DEFAULT 0,
  total_goals INT NOT NULL DEFAULT 0,
  place INT NOT NULL
);

CREATE TABLE Player (
  number INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  position VARCHAR(50) NOT NULL,
  age INT NOT NULL,
  games_played INT NOT NULL,
  height FLOAT NOT NULL,
  assists INT NOT NULL,
  country_name INT NOT NULL,
  FOREIGN KEY (country_name) REFERENCES country(name)
);
