DROP TABLE Country CASCADE CONSTRAINTS;
DROP TABLE Accolades CASCADE CONSTRAINTS;
DROP TABLE Matches CASCADE CONSTRAINTS;
DROP TABLE Player CASCADE CONSTRAINTS;
DROP TABLE Coach CASCADE CONSTRAINTS;
DROP SEQUENCE seqCounID;
DROP SEQUENCE seqPlayID;
DROP SEQUENCE seqMatchID;
DROP SEQUENCE seqCoachID;
DROP SEQUENCE seqAccID;

CREATE TABLE Country (
  cname VARCHAR(50) PRIMARY KEY,
  continent VARCHAR(50) NOT NULL,
  group_letter VARCHAR(1) NOT NULL,
  number_of_goals INT NOT NULL,
  placing VARCHAR(50) NOT NULL
);

CREATE SEQUENCE seqCounID INCREMENT BY 1 START WITH 1;

CREATE TABLE Player (
  pnumber INT NOT NULL,
  pname VARCHAR(50) NOT NULL,
  pposition VARCHAR(50) NOT NULL,
  age INT NOT NULL,
  games_played INT NOT NULL,
  height FLOAT NOT NULL,
  assists INT NOT NULL,
  goals INT NOT NULL,
  country_name VARCHAR(50) NOT NULL,
  PRIMARY KEY (pnumber, country_name),
  FOREIGN KEY (country_name) REFERENCES country(cname)
);

CREATE SEQUENCE seqPlayID INCREMENT BY 1 START WITH 1;

CREATE TABLE Coach (
  coname VARCHAR(50) PRIMARY KEY,
  age INT NOT NULL,
  country_name VARCHAR(50) NOT NULL,
  FOREIGN KEY (country_name) REFERENCES country(cname)
);

CREATE SEQUENCE seqCoachID INCREMENT BY 1 START WITH 1;

CREATE TABLE Matches (
  mtime VARCHAR(50) NOT NULL,
  mdate DATE NOT NULL,
  winner VARCHAR(50) NOT NULL,
  loser VARCHAR(50) NOT NULL,
  stage VARCHAR(50) NOT NULL,
  PRIMARY KEY (mdate, mtime)
);

CREATE SEQUENCE seqMatchID INCREMENT BY 1 START WITH 1;

CREATE TABLE Accolades (
  aname VARCHAR(150) PRIMARY KEY,
  adescription VARCHAR(1000) NOT NULL,
  recipient VARCHAR(150) NOT NULL
);

CREATE SEQUENCE seqAccID INCREMENT BY 1 START WITH 1;
